steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/third-strategy-489120-u3/whatsapp-backend/api:latest
      - .

images:
  - us-central1-docker.pkg.dev/third-strategy-489120-u3/whatsapp-backend/api:latest
